### ISSUE TITLE
Can't use System.Data in C#

### ISSUE THREAD

**Issue by TymurGubayev** [ashmind/SharpLab#102]
I can import the System.Data if language is Visual Basic ([1](https://sharplab.io/#f:vb/JIWwDg9gTgLgzgAgMoE84wKYgLAChSSyKrpYB0AIgIYxV4AKArgEYA2AlgMYIDCrVcRDzwJRCJmy7IWCALIAKAJQixqgCbsQCNTAQCEAOwwB3bTXNsMK1aI1aAHggC8CAEzWbjl44C0CAIweAKIGatLMeCFhfAJwQA==)) but the other way around doesn't work ([2](https://sharplab.io/#K4Zwlgdg5gBAygTxAFwKYFsDcBYAUKSWRFDAOgBEBDZSnXAB2ACMAbMAYxnZcpBBgDCeAN54Y4mI1YcYANwD2YACYwAsgAoAlGImjcEgzCo0AKpVaoYS6pTMWYAXhgRUAdyM27LVFrqGJkMjOwOiOMABMfv5cABao7ADWqEo6/nrRhhAhALTZUf4AvqkwRbgFQA=)): `The type or namespace 'Data' does not exist in the namespace 'System'` is shown on the line with `using System.Data;`.

**Comment by svick** [comment]
As far as I can tell, this is because for VB, `Microsoft.VisualBasic` and all its transitive references are included (`Microsoft.VisualBasic` references `System.Web`, which references `System.Data`). But `Microsoft.CSharp` does not reference `System.Data`.

I guess it would be nice if all common GAC assemblies were referenced?

**Comment by ashmind** [comment]
Thanks for reporting!

For now I plan to add the references explicitly, based on issues. E.g I'll add `System.Data` based on this one (probably within the next two days).

**Comment by ashmind** [comment]
@TymurGubayev Done, but note that it wouldn't work in `master` branch until #111 is resolved.
