### ISSUE TITLE
sharplab.io - main - connection lost

### ISSUE THREAD

**Issue by bernd5** [ashmind/SharpLab#1226]
currently sharplab.io is not working:

![grafik](https://user-images.githubusercontent.com/26689688/202266888-0f3a538b-1e7d-4db8-95cd-ad7dff11d20a.png)

@ashmind can you have a look? Thank you in advance!

**Comment by ashmind** [comment]
Thanks for reporting! I restarted the site so it should work for now, however I still need to investigate further, so I would like to keep this issue open.

As it is, it might break again in about 12 hours.

**Comment by bernd5** [comment]
Great - it works, again 👍👍👍
I observed it since some days - I use sharplab regulary, it is really great. Especially that you can have a look at lowered csharp, IL and JIT asm. And that you can share links to code.

As fallback I use https://dotnetfiddle.net, or when I need to reference nuget packages.
Let me know if you found the source of the issue.

**Comment by bernd5** [comment]
As you assumed, currently the service is unavailable again 😒

**Comment by ashmind** [comment]
Thanks -- this is now resolved. Root cause was another branch stuck on 100% CPU, which caused nightly deployments to time out, and leave the branch offline. Note that downtimes of around 2-3 mins per day around this time are still expected (not to say it can't be improved, but this was always the case).

(Btw I do plan to allow NuGet packages eventually, but there is no definite timeline for it)
