### ISSUE TITLE
Decompile using to try/finally

### ISSUE THREAD

**Issue by ashmind** [ashmind/SharpLab#185]

**Comment by davidwengier** [comment]
I thought I'd have a go at fixing this, but having lots of trouble building the solution in Visual Studio. I'm using 2017, but looks like my .NET Core 2.0 installation was broken.  
I've fixed that but I'm not getting errors because Mono.Cecil is being compiled without READ_ONLY defined, but Mono.Cecil.Pdb isn't. It makes me wonder if the master branch is currently building correctly at all?

Are there any other tips to getting things to build? I get errors in Visual Studio about "'$(NETStandardImplicitPackageVersion)' is not a valid version string". Has anyone seen that, or know how to fix it?

I've tried various `dotnet restore` and `nuget restore` from various spots, and it seemed to nudge things along a bit, but not solve any problems.

I might have done something wrong with the submodules though, I've never used them before. I just ran `git submodule update --recursive --remote --init` from the root directory and it seemed to get everything correctly.

Thanks for the help.

**Comment by ashmind** [comment]
@davidwengier Interesting -- and I don't think you did anything wrong with the submodules either. I'll try on a different machine and see if I can get the same problem. Overall `master` branch should be building correctly -- I work in `edge`, but `master` is periodically fast-forwarded to `edge`, and both build successfully on Azure.

Unfortunately due to some other plans (travel), I might not have time to follow up before next week.

**Comment by davidwengier** [comment]
Thanks, I completely understand. I'll keep plugging away too, as I think the submodules might be somehow incorrect actually.

In https://github.com/ashmind/ILSpy github is showing "cecil @ 53df0bc", however I have cecil at the latest commit 3bd25b. Looks like there are some breaking changing in that (eg the Name property on VariableDefinition is gone) so I'll start with trying to pin those submodules matching what is shown in github.

**Comment by ashmind** [comment]
@davidwengier Hmm, I think `--remote` in your submodule update might be a problem. I've got a fresh clone and ran `git submodule update --recursive --init`, and after that it builds (at third try since I have a build bug that I'll need to diagnose).

I'll definitely need to improve experience here, but not sure when I'll have time.

**Comment by davidwengier** [comment]
Thank you! I did the same, and sure enough the 3rd build was a success. I'll submit a PR for this issue in a few minutes.

Thank you again for the help.

**Comment by ashmind** [comment]
@davidwengier Great -- merged, thanks! Might take up to 10 mins to be deployed.
