### ISSUE TITLE
Namespace System.Threading.Tasks is not allowed. 

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#221]
> Unbreakable.AssemblyGuardException: Namespace System.Threading.Tasks is not allowed. 

Why is this?

**Comment by ashmind** [comment]
@jnm2 It only allows the namespaces that were explicitly whitelisted.
Tasks is harder to allow than some others, so I haven't done that yet, even though it's ashmind/Unbreakable#1.

The problem with tasks is making sure people can't deadlock -- it's not unsolvable, but I haven't had time to look into it yet. Tbh I'm less motivated to work on code execution in SharpLab since MS made https://try.dot.net, so the timelines are unclear.

**Comment by jnm2** [comment]
Oh, cool. What's wrong with deadlocking? Not interested in aborting threads or going out of proc?

**Comment by ashmind** [comment]
Aborting threads is not that easy, need to know which ones and when to abort -- also I think .NET Core doesn't have that, and my long-term plan is to migrate to .NET Core at some point.

Out-of-process is a reasonable solution, but has some overhead -- I wanted to try something different with Unbreakable and I don't want to give up on that unless I run into an impossible problem.

**Comment by ashmind** [comment]
Hi @jnm2, this is now allowed (new Run mode is out of process).
