### ISSUE TITLE
Cannot use System.Xml.Linq

### ISSUE THREAD

**Issue by molinch** [ashmind/SharpLab#236]
We cannot import System.Xml.Linq is this a design choice ?
This prevents using Linq to XML.

**Comment by ashmind** [comment]
@molinch Thanks for the question. I only allow APIs after security/performance review, and I haven't yet done one for `XDocument` etc. 

Since MS released https://try.dot.net the "Run" mode has lower priority for me than everything else, so I can't promise any specific timeline for this. If this is important, please use https://try.dot.net and https://dotnetfiddle.net instead.

**Comment by svick** [comment]
It's not just about Run mode, [`System.Xml.Linq` won't even compile](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEAMACFBGAdADQFsAbXAGRgDsBHAbiA===).

**Comment by ashmind** [comment]
@svick Thanks -- fair enough -- it's not referenced. I'll clarify.
@molinch Do you need System.Xml.Linq for "Run" mode, on any other?

**Comment by molinch** [comment]
Thanks for the feedback @ashmind 
Yes at that time it was basically for the Compiler/IL mode, not for the Run mode.

You are right, for Run mode many other websites exists, I usually rely on https://dotnetfiddle.net/
However your website is pure gold to get what the compiler is doing and how to optimize your code.

**Comment by ashmind** [comment]
Thanks! That should be easier -- can't promise any specific time, but I'll try to do soon-ish.

**Comment by ashmind** [comment]
Should work now -- in all modes except Run.
