### ISSUE TITLE
RyuJIT support

### ISSUE THREAD

**Issue by exyi** [ashmind/SharpLab#328]
The online C# to Assembly compilation is an amazing tool. It would be however even better to support x64 currenct version of RyuJIT, as it can generate much better code sometimes, so the results may be a bit misleading.

**Comment by svick** [comment]
What do you consider to be "current version of RyuJIT"?

If you mean the one that's in .Net Framework 4.7, then I believe that's what is used when you select "x64" in the main drop-down. (It's otherwise used to select Roslyn branch, which might be confusing you.)

If you mean the one that's in .Net Core, then I think this is effectively a duplicate of https://github.com/ashmind/SharpLab/issues/273.

**Comment by exyi** [comment]
Thank you, I did not know that, switching to x64 seems to work. I was just a bit confused that it's in the branch selection menu and it's not awailable at all for F#.
