### ISSUE TITLE
Unbreakable.AssemblyGuardException: Type System.Index is not allowed.

### ISSUE THREAD

**Issue by RikkiGibson** [ashmind/SharpLab#424]
The following code which tries to use the index/range feature won't run.

```cs
public static class Program {
    public static void Main() {
        var arr = new[] { 1, 2, 3, 4, 5 };
        Console.WriteLine(arr[0..1]);
    }
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABAJgEYBYAKDIAYayBmAAgG8aWuWzT3PuggG4QELUWIC8LTHADuAbQC67FuSQtSGphoAsGgKwsAvgG4BgrsXIBOABQSFdAHTPySgJTnqg4zWNAA

**Comment by ashmind** [comment]
Thanks for reporting! I'll take a look. Only recently switched branches to .NET Core so haven't added those types yet.

**Comment by ashmind** [comment]
Fixed in Default, should be available in `master` and other Roslyn branches in 3-4 hours.

**Comment by ashmind** [comment]
Hmm, finally deployed, but now it's failing on `GetSubArray`, I'll keep this open for a bit more.

**Comment by ashmind** [comment]
Fixed in `.NET Core (x64)`:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7NAExAGoAfAAQCYBGAWAChqAGR6gZgAIBvRz/ztSo8+AsQDcAhlE7SZAXk54YAdwDaAXR6caaTlT3s96TgFZOAXwDcosfwo0AnAAo5a5gDoPNDQEobDGIWjBZAA

Will be deployed on other branches (e.g. `master`) later.
That's currently manual until #427, so I can't give a specific estimate (but no longer than #427).
