### ISSUE TITLE
I can't even test my loops

### ISSUE THREAD

**Issue by Happypig375** [ashmind/SharpLab#475]
```cs
using System;
public static class Program {
    public static void Main() {
        for (sbyte i = -36 + 1; i != -36; i++)
            if(-45 <= i && i <= -40)
                Console.WriteLine(i);
    }
}
```
```
-45
-44
Exception
Unbreakable.Runtime.RateGuardException: Operation limit reached.
   at Unbreakable.Runtime.Internal.RuntimeGuard.EnsureRate()
   at Unbreakable.Runtime.Internal.RuntimeGuard.GuardJump()
   at Program.Main()
```
[C# Pad](https://csharppad.com) provides a much better experience compared to SharpLab's run mode.

**Comment by ashmind** [comment]
To be honest I don't really see it as a competition -- if the other tool is better then it makes sense to use it for now? The restrictions are quite strict at the moment because the goal is to preserve the performance for all users, without paying a lot for hosting.

Longer term I plan to provide a WebAssembly version which will have no restrictions at all, and maybe containers which could manage this in a nicer way.

I'll keep this open in case I might think of another way to improve experience here.

**Comment by ashmind** [comment]
Hi @Happypig375, this is resolved in the new Run model.
