### ISSUE TITLE
Roslyn branch build is failing  (Connect-AzAccount)

### ISSUE THREAD

**Issue by ashmind** [ashmind/SharpLab#478]
E.g. see https://github.com/ashmind/SharpLab/runs/521795660?check_suite_focus=true

**Comment by tannergooding** [comment]
It's worth noting that starting with the failing build linked, `Install Modules` now prints a new warning:
> WARNING: Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide

Given `Uninstall-AzureRM` is explicitly being run, perhaps its just due to the ordering here...

There is then a separate warning that already existed:
> WARNING: Running this cmdlet in PowerShell Core will only remove the modules from PowerShell Core. Please rerun this cmdlet in a PowerShell 5.1 session to remove the modules from PowerShell 5.1.

The `Update-All` command is using just `powershell` rather than `pwsh`, so perhaps it's running against the wrong version?

**Comment by ashmind** [comment]
@tannergooding Thanks, good point about `powershell` vs `pwsh`!

**Comment by ashmind** [comment]
(Had to sort out few more things to improve stability, but should be more stable now)
