### ISSUE TITLE
support limited DllImport for JIT code analysis

### ISSUE THREAD

**Issue by vvuk** [ashmind/SharpLab#528]
It would be nice to be able to examine generated JIT tranmpoline/marshal code for DllImport.  I think all that would be needed is for some named native library to be available, with some named entry points (they don't have to match what the declaration is in C#, just the names have to exist).  I'd like to be able to look at the generated JIT code for something like:

```
using System;
using System.Runtime.InteropServices;
public class C {
    [DllImport("native", EntryPoint = "entry1")]
    public static extern void FooFn([MarshalAs(UnmanagedType.U1)] ref bool thing);
    
    public static void M() {
        bool q = true;
        FooFn(ref q);
    }
}
```

this currently fails with
```
System.DllNotFoundException: Unable to load DLL 'native' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

when trying to look at `JIT Asm` results.

**Comment by svick** [comment]
Is there a reason why you can't use some library that is already guaranteed to exist? Since SharpLab seems to be running on Windows, [the following works for me](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBJFmKCAA4BlPgDdWYGLgDcAWABQC4gCZyAYQUBvBeV3kA2gBEANsa74B0DAAoARAGs+TGMYDMymgBNTttOQCiLFAAngAKEKws5AC85LZqsNgYMABirMYwtgCUALo6esSulFRI5DAIyVBMlCjkKRAQKUzW+gCy2FC4ABbYxgCCuNYAqkz42EzYAOYwngAqwQKcQ1S55LAAZuTADcbkGF2Rk1ly8nrk+bqFxaXEta3WWeTap2d62xC7AI4xe1AMMCdXnp6o1mhtyJ9jhdyABfBQwoA):

```c#
[DllImport("kernel32.dll", EntryPoint = "CreateFile")]
```

**Comment by vvuk** [comment]
Gah. No. That should work fine, I tried a ton of things I could think of but I assumed it was running on Linux.
