### ISSUE TITLE
Unexpected InvalidProgramException unless using x64

### ISSUE THREAD

**Issue by binki** [ashmind/SharpLab#714]
https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoAZWARwG5jiA3CZcgYwHsAbVGBgBncgF5yMAKYB3SgFYAPAApYCchDjl15YAEptVUgD4A2gF1yAb2Ll75AB4STT6hAmSAtHnIB+cgAiCEDyEDcIagAVXgBlBGRYAHMVQzsHZ3FXR3dPch9/II8AQklSUPCVHJKy/Wi4hOTUuHT7TOzc8W9fAODyUvI8CvIq3IG8Opj4xJgUtKIHJxcIvILemvIKDAxNfskhsJHqvc3ybZXxyYaZuZaiAF8WIgAzXmRpCG4ACxGOLhU+IJhNpAUIYABJGAAE2kjn0OhgPAEYJE1Fi0n40m4CBUAO0UHhWRG3Hx+jJxFsCwcUGexORwkhMOcrlI8IAwrxRAJpNQAOqJBDSFSBAA6CEC+ieiw5XMxfIFQtBwlxPm0PjJkuI92IVAAnKknsRXv8/rsykxdkpyABmC0QADU9v0FNa5GNH2+v04dKB8CRvsZsPhsH9KLRGKxOLxOkJrmjBPJVPslMWixpPrBgeZm3ZnJE3PlUEFwrFEqlqfsMvzcv5RcV9JguK0ObJ5fs2qTlDw+s1DyAA

This runs fine for me on .netcore2.1, .netcore3.1, .netcore5 (all on Windows), and on .netfx-4.8 (528372). I don’t have insight into how the website runs things, so I don’t know if this is a bug that needs to be reported to .net upstream…?

Thanks.

**Comment by ashmind** [comment]
I've tried it and cannot reproduce anymore -- since original report said x64 worked fine, it might actually have already been fixed, since branches such as `main` are updated with a bit of a delay compared to x64 and others.

Alternatively, that might have actually been a Roslyn bug that was since fixed.

Please let me know if you see it again.
